### ISSUE TITLE
kunyu init    not found

### ISSUE THREAD

**Issue by yuanlisama** [knownsec/Kunyu#21]
kunyu init --apikey <your zoomeye key> --seebug <your seebug key>
输入apikey后显示 kunyu: command not found

**Comment by CTRLCCT** [comment]
使用pip3 install kunyu -i https://pypi.tuna.tsinghua.edu.cn/simple下载的kunyu然后执行kunyu init --apikey --seebug
输入apikey后显示 kunyu: command not found咋搞？

**Comment by CTRLCCT** [comment]
外加我在kali上照着这https://github.com/knownsec/Kunyu/连接弄，在执行kunyu console后报出一下：
Traceback (most recent call last):
  File "/usr/local/bin/kunyu", line 33, in <module>
    sys.exit(load_entry_point('kunyu==1.7.2', 'console_scripts', 'kunyu')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/kunyu", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/dist-packages/kunyu-1.7.2-py3.11.egg/kunyu/console.py", line 17, in <module>
    from kunyu.core.console import KunyuInterpreter
  File "/usr/local/lib/python3.11/dist-packages/kunyu-1.7.2-py3.11.egg/kunyu/core/__init__.py", line 15, in <module>
    import grequests
ModuleNotFoundError: No module named 'grequests'
这咋搞？
