### ISSUE TITLE
Error on latest kali linux purple 

### ISSUE THREAD

**Issue by Visalyputra** [knownsec/Kunyu#64]
How to solve this error? 

Traceback (most recent call last):
  File "/usr/local/bin/kunyu", line 33, in <module>
    sys.exit(load_entry_point('kunyu==1.7.2', 'console_scripts', 'kunyu')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/kunyu", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/dist-packages/kunyu-1.7.2-py3.11.egg/kunyu/console.py", line 17, in <module>
    from kunyu.core.console import KunyuInterpreter
  File "/usr/local/lib/python3.11/dist-packages/kunyu-1.7.2-py3.11.egg/kunyu/core/console.py", line 23, in <module>
    from kunyu.core.zoomeye import ZoomEye
  File "/usr/local/lib/python3.11/dist-packages/kunyu-1.7.2-py3.11.egg/kunyu/core/zoomeye.py", line 25, in <module>
    from pocsuite3 import set_paths
  File "/usr/local/lib/python3.11/dist-packages/pocsuite3/__init__.py", line 11, in <module>
    from .cli import module_path
  File "/usr/local/lib/python3.11/dist-packages/pocsuite3/cli.py", line 12, in <module>
    from pocsuite3.lib.core.option import init
  File "/usr/local/lib/python3.11/dist-packages/pocsuite3/lib/core/option.py", line 11, in <module>
    import socks
  File "/usr/local/lib/python3.11/dist-packages/socks.py", line 58, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.11/collections/__init__.py)

**Comment by wikiZ** [comment]
Probably because your python version is too high,

**Comment by wikiZ** [comment]
Probably because your python version is too high,you can use command "pip install kunyu" to solved this issue.

**Comment by wikiZ** [comment]
You need to get to https://www.zoomeye.org/ Register and get the api-key to initialize in and replace the key
