### ISSUE TITLE
运行kunyu console提示错误

### ISSUE THREAD

**Issue by myzzs** [knownsec/Kunyu#67]
Traceback (most recent call last):
  File "/usr/local/bin/kunyu", line 11, in <module>
    load_entry_point('kunyu==1.7.2', 'console_scripts', 'kunyu')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/kunyu-1.7.2-py3.8.egg/kunyu/console.py", line 17, in <module>
    from kunyu.core.console import KunyuInterpreter
  File "/usr/local/lib/python3.8/dist-packages/kunyu-1.7.2-py3.8.egg/kunyu/core/console.py", line 23, in <module>
    from kunyu.core.zoomeye import ZoomEye
  File "/usr/local/lib/python3.8/dist-packages/kunyu-1.7.2-py3.8.egg/kunyu/core/zoomeye.py", line 41, in <module>
    from kunyu.core.PupilMain import Pupil, ParaInit
  File "/usr/local/lib/python3.8/dist-packages/kunyu-1.7.2-py3.8.egg/kunyu/core/PupilMain.py", line 13, in <module>
    from kunyu.lib import TrackUrl
  File "/usr/local/lib/python3.8/dist-packages/kunyu-1.7.2-py3.8.egg/kunyu/lib/TrackUrl.py", line 14, in <module>
    from requests_html import HTMLSession
  File "/usr/local/lib/python3.8/dist-packages/requests_html.py", line 14, in <module>
    from lxml.html.clean import Cleaner
  File "/usr/local/lib/python3.8/dist-packages/lxml/html/clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.

**Comment by wikiZ** [comment]
请使用pip install kunyu安装。

**Comment by CTRLCCT** [comment]
使用pip3 install kunyu -i [https://pypi.tuna.tsinghua.edu.cn/simple下载的kunyu然后执行kunyu](https://pypi.tuna.tsinghua.edu.cn/simple%E4%B8%8B%E8%BD%BD%E7%9A%84kunyu%E7%84%B6%E5%90%8E%E6%89%A7%E8%A1%8Ckunyu) init --apikey --seebug
输入apikey后显示 kunyu: command not found咋搞？

**Comment by wikiZ** [comment]
你看下当前用户有没有权限
